### PR TITLE
feat: add .imports_keys() method to ImportMap

### PR DESCRIPTION
**Pull request by kitsonk**
This is in support of denoland/deno#13619.

### CODE REVIEW

**Review by dsherret — APPROVED** [review]
LGTM, but maybe give the PR a title specific to this repo before merging.

By the way, there will be a breaking change upgrading the repo for the CLI. It now uses `import_map::parse_something_function_name_I_forget_and_am_lazy_to_lookup(...)`. Should be easy to switch to.

**Comment by kitsonk** [comment]
> By the way, there will be a breaking change upgrading the repo for the CLI. It now uses `import_map::parse_something_function_name_I_forget_and_am_lazy_to_lookup(...)`. Should be easy to switch to.

Yeah, I have already had to address it to get it to compile upstream.

**Comment by kitsonk** [comment]
_sign_ I changed the title of the PR and assumed it would change it when I merged, but forgot it doesn't... sorry...

**Comment by dsherret** [comment]
Haha! No problem. That's gotten me so many times (even within this past week)

**Pull request merged**
