### PR TITLE
v0.15.0

### PR DESCRIPTION
**Pull request by bartlomieju**
This commit adds two APIs that allow to parse
from JSON text of JSON value ignoring unknown
keys. Required for https://github.com/denoland/deno/pull/17478

### CODE REVIEW

**Comment by dsherret** [comment]
Could you give this a better title? I don't like this API. We should be able to pass a `Value` that only has the `imports` and `scopes` to this.

**Comment by bartlomieju** [comment]
> Could you give this a better title? I don't like this API. 

Title to the PR or the API name? 

> We should be able to pass a `Value` that only has the `imports` and `scopes` to this.

I can remove the API for passing `Value` but we will need the API for parsing from text to ignore unknown keys

**Comment by dsherret** [comment]
> Title to the PR or the API name?

To the PR.

> I can remove the API for passing Value but we will need the API for parsing from text to ignore unknown keys (ie. passing whole deno.json file).

I'm not sure about this. This doesn't seem like a concern for the import_map crate.

**Comment by bartlomieju** [comment]
Closing in favor of https://github.com/denoland/import_map/pull/53

**Pull request closed without merging**
